### ISSUE TITLE
Programming guide chapter 6 is messed up

### ISSUE THREAD

**Issue by Pouja** [chukong/cocos-docs#873]
http://cocos2d-x.org/docs/programmers-guide/6/index.html, see [6.md](https://github.com/chukong/cocos-docs/blob/v3-unified-documentation/programmers-guide/chapters/6.md)

The alignments are all over the place. It seems it goes wrong after the first code block.

**Comment by slackmoehrle** [comment]
Thanks. I will fix this today.

**Comment by slackmoehrle** [comment]
fix and deployed. Thank you again.
