### ISSUE TITLE
Hidden Content

### ISSUE THREAD

**Issue by stevetranby** [chukong/cocos-docs#881]
I think search as first goto is great. I think the docs are great (or at least always improving). 
I think the previous style or theme was superior because this latest theme requires searching for some content. This is due to either being inaccessible or due to mis-cataloging.

Example: search for ScrollView, opens page on Containers, how do you get here without searching?

Maybe this is something you've already fixed in v.next?

**Comment by slackmoehrle** [comment]
@stevetranby Thanks Steve. Yes, I see what you are saying.

This is actually a limitation in MKDocs where you can only have 2 layers of nested content. I should check and see if that has been resolved by now. 

This doesn't help, but in your example of ScrollView, when the page opens it has a URL of:
http://slackmoehrle.github.io/editors_and_tools/studio-chapters/chapter3/UI/Containers/en/index.html#4-scrollview

Menu navigation would be: __Contents -> Editors & Tools -> Studio__
Scroll to __Editor/UI__ and under that is __Containers__

I'll come up with a better way to do this. I am taking a lot of legacy stuff and bringing it under one umbrella. Ricardo already mentioned having the left had side TOC having a bread crumb trail or something too.

**Comment by stevetranby** [comment]
The docs for cocos creator inside the app has a much better layout IMHO, and again I still prefer the default older MKDocs layout. Mainly the new cocos2d-x docs just feel very large (things could probably use slightly smaller fonts and spacing) and the code sections could probably have a little more of a look (maybe slightly darker background) with syntax highlighting.

I'll continue to look for typos and more importantly code errors as I am working on building out a sample project for more advanced stuff along with those inside the docs.

**Comment by slackmoehrle** [comment]
Thanks Steve! I will take a look at how the docs are laid out inside the app. TBH, I haven't looked at them outside of GitHub and Docs/.

**Comment by slackmoehrle** [comment]
This has been fixed in the next docs iteration. Thank you for reporting it.
