### ISSUE TITLE
Problem in installing and running on debian linux

### ISSUE THREAD

**Issue by AllanDaemon** [chukong/cocos-docs#882]
I'm trying to install it to a debian sid (unstable) install. I'm following these links:

http://www.cocos2d-x.org/wiki/Linux_Installation_and_Setup
http://www.cocos2d-x.org/docs/installation/F/

I downloaded the latest stable .zip source (3.10). I installed the dependencies manually, but I didn't install the PPA for `GCC4.9` as i already have `GCC5.3`. The library `glfw3` doesn't exist in Sid, but I installed `libglfw3 libglfw3-dev` instead.

I compiled successfully the code. The next and latest step is running the tests. There it's when it failed with missing `libfmod.so.6`.

```
user@host:~/src/cocos2d-x/build/linux-build/bin$ ./cpp-tests/cpp-tests 
./cpp-tests/cpp-tests: error while loading shared libraries: libfmod.so.6: cannot open shared object file: No such file or directory
```

I tried to search solutions but I couldn't find anything that helped me. Did i missed some step in the tutorial? Could it be something in Ubuntu missing in Debian pure packages? Or something that is missing in Sid? Or there are missing some step in the documentation?

**Comment by AllanDaemon** [comment]
It will fail also running a simple hello world. I created a new project with the default template, and asked to run. After tthe successful compilation, the run gave the same problem.

```
$ cocos new -l cpp dhc
$ cd dhc
$ cocos run -p linux
(...)
[100%] Linking CXX static library ../../lib/libcocos2d.a
[100%] Built target cocos2d
Scanning dependencies of target MyGame
[100%] Building CXX object CMakeFiles/MyGame.dir/Classes/AppDelegate.cpp.o
[100%] Building CXX object CMakeFiles/MyGame.dir/Classes/HelloWorldScene.cpp.o
[100%] Building CXX object CMakeFiles/MyGame.dir/proj.linux/main.cpp.o
[100%] Linking CXX executable bin/MyGame
[100%] Built target MyGame
Build succeed.
Deploying mode: debug
Starting application.
running: '/home/user/code/dhc/bin/debug/linux/MyGame'

/home/user/code/dhc/bin/debug/linux/MyGame: error while loading shared libraries: libfmod.so.6: cannot open shared object file: No such file or directory
Error running command, return code: 127.
```

**Comment by AllanDaemon** [comment]
I found a workaround to this. 

I found this binaries in cocos-2d Github account: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/tree/v3/linux-specific/fmod/prebuilt/64-bit

I downloaded those 2 .so binaries and copied them to `/usr/lib` (as root), and then called the command `ldconfig` (also as root). Now the HelloWorld game and the game test seems to be worlking all right.

```
user@host:~/src$ git clone https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin.git
Cloning into 'cocos2d-x-3rd-party-libs-bin'...
remote: Counting objects: 12337, done.
remote: Total 12337 (delta 0), reused 0 (delta 0), pack-reused 12337
Receiving objects: 100% (12337/12337), 486.18 MiB | 568.00 KiB/s, done.
Resolving deltas: 100% (3230/3230), done.
Checking connectivity... done.
Checking out files: 100% (2630/2630), done.

user@host:~/src$ cd cocos2d-x-3rd-party-libs-bin/linux-specific/fmod/prebuilt/64-bit

user@host:~/src/cocos2d-x-3rd-party-libs-bin/linux-specific/fmod/prebuilt/64-bit$ ls -lh
total 3.1M
-rwxr-xr-x 1 user user 1.7M Feb 21 01:19 libfmodL.so
-rwxr-xr-x 1 user user 1.5M Feb 21 01:19 libfmod.so

user@host:~/src/cocos2d-x-3rd-party-libs-bin/linux-specific/fmod/prebuilt/64-bit$ sudo su

root@host:/home/user/src/cocos2d-x-3rd-party-libs-bin/linux-specific/fmod/prebuilt/64-bit# cp * /usr/lib/

root@host:/home/user/src/cocos2d-x-3rd-party-libs-bin/linux-specific/fmod/prebuilt/64-bit# ldconfig
```

**Comment by slackmoehrle** [comment]
I haven't every tried on Debian. I did go through the Instructions on Ubuntu and they worked.

**Comment by slackmoehrle** [comment]
you resolved this on the forums, correct?

**Comment by AllanDaemon** [comment]
I tried (partially) in Ubuntu and this library was missing as well.

I didn't used forum. I'll create a account though.
