### ISSUE TITLE
Programmers Guide -> Formatting is all screwed up.

### ISSUE THREAD

**Issue by crobertsbmw** [chukong/cocos-docs#896]
The formatting is all screwed up on all the chapters. See chapter 9:

http://www.cocos2d-x.org/docs/programmers-guide/9/index.html

The first 4 paragraphs are all wrapped in a code block and then the css is all wonky for the rest of the page. 
Chapter 11 has the same issue of the entire thing being wrapped in a code block.
Chapter 6 still has the issue of all the content being gone after the first code block. 
Chapter 7 and 8 might also have missing content, but I can't remember what's supposed to be there.

**Comment by crobertsbmw** [comment]
Which files need to be edited to fix these issues? Maybe I could take a stab at creating a pull request.

**Comment by slackmoehrle** [comment]
I apologize for this mistake. It happened when I mis-commented out a </div> for an incomplete JavaScript code block. Weird, it did not look incorrect when I tested in Marked2.app.

This is being deployed out to production as I write this.
