### ISSUE TITLE
Very confusing documentation

### ISSUE THREAD

**Issue by LeventDal** [chukong/cocos-docs#897]
The tutorials are hard to trace, everything seems like they're  disconnected, some things are outdated, Example projects have Chinese comments inside.
Some steps are detailed and then there are huge gaps between next steps. 
There can be lots of spanning outcomes but they're not handled or mentioned.

I think this documentation and tutorials themselves are a mace, and they consume more time than being helpful in my opinion.

**Comment by slackmoehrle** [comment]
Can you tell me where you are referring to so I can follow it? This will allow me to see first hand and figure out how we make the docs better. Thank you for the feedback.

**Comment by slackmoehrle** [comment]
Closing as no comment back.
