### ISSUE TITLE
Cocos Creator -> Access Node Component (bad link)

### ISSUE THREAD

**Issue by iPruch** [chukong/cocos-docs#899]
Hello. I was taking a look at the new Cocos Creator and its documentation, and toying with Cocos Creator I wanted to access Node properties, so I went to the documentation and found Cocos Creator -> Scripting -> Access Node Component: 

http://cocos2d-x.org/docs/editors_and_tools/creator-chapters/scripting/access-node-component/

But it instead talks about creating and destroying nodes. Curiously, it is almost 100% the same to this page (with very little differences):

http://cocos2d-x.org/docs/editors_and_tools/creator-chapters/scripting/create-destroy/

So I guess there's an error there!

**Comment by slackmoehrle** [comment]
Thank you, I will take a look!

**Comment by slackmoehrle** [comment]
This will be fixed in the next round for Creator 1.0.2. Which is this coming week.

**Comment by slackmoehrle** [comment]
This has been fixed in the next docs iteration. Thank you for reporting it.
