### ISSUE TITLE
JS Programmers Guide is missing lots of information

### ISSUE THREAD

**Issue by traviswimer** [chukong/cocos-docs#900]
I've noticed that the Programmers Guide for Javascript is missing a lot of code examples and also has some incorrect examples.

I see that there are placeholders for the JS examples. Would the maintainers appreciate pull requests that add examples/fix problems, or is this already in the process of being added?

**Comment by slackmoehrle** [comment]
I would absolutely appreciate pull requests! This is on my list. We are making a monthly documentation roadmap now too so we can make consistent progress on the docs.

**Comment by slackmoehrle** [comment]
This is in progress.
