### ISSUE TITLE
Javascript errors on all pages of documentation

### ISSUE THREAD

**Issue by traviswimer** [chukong/cocos-docs#905]
I noticed there are Javascript errors on all pages of the documentation, because they are including a bunch of `<script>` tags that load the `.js` files for the tutorial inside http://www.cocos2d-x.org/docs/tutorials/javascript/parkour-game-with-javascript-v3.0/

**Comment by slackmoehrle** [comment]
Yes, this was put here temporarily and never removed. Now, it looks like we are adding it back. I will fix. Thank you.

**Comment by slackmoehrle** [comment]
This is now fixed in our upcoming new docs.
