### ISSUE TITLE
ccp-test build getting failed for android

### ISSUE THREAD

**Issue by ashiqsayyad** [chukong/cocos-docs#942]
Hi,

I downloaded the cocos2d-x-3.15 and followed the instructions to build it for android but build is getting failed with following error. I used following command

python android-build.py -p 21 cpp-tests

and build is getting failed with following errors
==============================================================

cocos compile -p android -s D:\Ashiq\AshiqOldData\Ashiq\MyLearning\cocos\cocos2d-x-3.15\build\..\tests\cpp-tests --ndk-mode debug --app-abi armeabi-v7a --ap android-21
Building mode: debug
Using Eclipse project : D:\Ashiq\AshiqOldData\Ashiq\MyLearning\cocos\cocos2d-x-3.15\tests\cpp-tests\proj.android
running: '"D:\Ashiq\android-sdk-windows\tools\android" update project -t android-21 -p D:\Ashiq\AshiqOldData\Ashiq\MyLearning\cocos\cocos2d-x-3.15\tests\cpp-tests\proj.

Updated project.properties
Updated local.properties
Updated file D:\Ashiq\AshiqOldData\Ashiq\MyLearning\cocos\cocos2d-x-3.15\tests\cpp-tests\proj.android\proguard-project.txt
running: '"D:\Ashiq\android-sdk-windows\tools\android" update lib-project -p D:\Ashiq\AshiqOldData\Ashiq\MyLearning\cocos\cocos2d-x-3.15\cocos\platform\android\java -t

Updated project.properties
Updated local.properties
Updated file D:\Ashiq\AshiqOldData\Ashiq\MyLearning\cocos\cocos2d-x-3.15\cocos\platform\android\java\proguard-project.txt
Building native...
NDK build mode: debug
running: '"D:\Ashiq\android-sdk-windows\android-ndk-r12\ndk-build" -C D:\Ashiq\AshiqOldData\Ashiq\MyLearning\cocos\cocos2d-x-3.15\tests\cpp-tests\proj.android -j4 APP_A

Android NDK: WARNING: APP_PLATFORM android-21 is larger than android:minSdkVersion 9 in ./AndroidManifest.xml
make: Entering directory `D:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/tests/cpp-tests/proj.android'
[armeabi-v7a] "Gdbserver      ": "[arm-linux-androideabi-4.9] libs/armeabi-v7a/gdbserver"
[armeabi-v7a] "Gdbsetup       ": "libs/armeabi-v7a/gdb.setup"
[armeabi-v7a] "Compile++ arm  ": "cpp_tests_shared <= main.cpp"
[armeabi-v7a] "Compile++ arm  ": "cpp_tests_shared <= ActionManagerTest.cpp"
process_begin: CreateProcess(NULL, D:/Ashiq/android-sdk-windows/android-ndk-r12/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-and
-ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/cocos/3d/.. -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/cocos/editor-support/spine/.. -I
5/cocos -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/cocos/. -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/cocos/.. -ID:/Ashiq/AshiqOld
ing/cocos/cocos2d-x-3.15/cocos/../external/clipper -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/external/websockets/prebuilt/android/../../include/andr
./include/android -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/external/tiff/prebuilt/android/../../include/android -ID:/Ashiq/AshiqOldData/Ashiq/MyLea
ck -Wformat -Werror=format-security -Wno-deprecated-declarations -D__STDC_LIMIT_MACROS=1 -fexceptions -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char
make (e=2): The system cannot find the file specified.
make: *** [obj/local/armeabi-v7a/objs-debug/cpp_tests_shared/main.o] Error 2
make: *** Waiting for unfinished jobs....
process_begin: CreateProcess(NULL, D:/Ashiq/android-sdk-windows/android-ndk-r12/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-and
-x-3.15/cocos/editor-support/cocosbuilder/.. -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/cocos/3d/.. -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/co
qOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/cocos -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/cocos/. -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/coco
i/sweep -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/cocos/../external/clipper -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/external/w
2d-x-3.15/external/jpeg/prebuilt/android/../../include/android -ID:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/external/tiff/prebuilt/android/../../includ
jni -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -Wno-deprecated-declarations -D__STDC_LIMIT_MACROS=1 -fexceptions -frtti -DCC_ENABLE_CH
make (e=2): The system cannot find the file specified.
make: *** [obj/local/armeabi-v7a/objs-debug/cpp_tests_shared/__/__/Classes/ActionManagerTest/ActionManagerTest.o] Error 2
make: Leaving directory `D:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/tests/cpp-tests/proj.android'
Error running command, return code: 2.
Build dynamic library for project [ D:\Ashiq\AshiqOldData\Ashiq\MyLearning\cocos\cocos2d-x-3.15\build\..\tests\cpp-tests ] failed!

**Comment by ashiqsayyad** [comment]
anybody looking into this issue..
Please help as its urgent for me and I tried with cppemtytest also on android studio but build is getting failed with following error

D:\Ashiq\AshiqOldData\Ashiq\MyLearning\cocos\cocos2d-x-3.15\external\bullet\BulletMultiThreaded\SpuNarrowPhaseCollisionTask\SpuGatheringCollisionTask.cpp
Error:(1430, 1) opening dependency file D:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/tests/cpp-empty-test/proj.android-studio/app/build/intermediates/ndkBuild/debug/obj/local/armeabi/objs-debug/bullet_static/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuGatheringCollisionTask.o.d: No such file or directory
Error:(1430, 1) fatal error: opening dependency file D:/Ashiq/AshiqOldData/Ashiq/MyLearning/cocos/cocos2d-x-3.15/tests/cpp-empty-test/proj.android-studio/app/build/intermediates/ndkBuild/debug/obj/local/armeabi/objs-debug/bullet_static/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuGatheringCollisionTask.o.d: No such file or directory
Information:BUILD FAILED

**Comment by slackmoehrle** [comment]
This is the wrong repo to report this. Closing issue.
